import os
import sys

import anthropic
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from rank_bm25 import BM25Okapi

app = FastAPI()

_HERE = os.path.dirname(os.path.abspath(__file__))

# Ensure the api/ directory is on sys.path so `papers_data` can be imported.
# Vercel bundles Python source imports automatically, making this more reliable
# than includeFiles for arbitrary data files.
if _HERE not in sys.path:
    sys.path.insert(0, _HERE)

_corpus: list[tuple[str, str]] = []
_bm25: BM25Okapi | None = None
_load_error: str = ""


def _load_index() -> None:
    global _corpus, _bm25, _load_error
    try:
        from papers_data import CORPUS  # generated by scripts/index_papers.py
        _corpus = list(CORPUS)
        _bm25 = BM25Okapi([c[0].lower().split() for c in _corpus])
        papers = list(dict.fromkeys(p for _, p in _corpus))
        print(f"[bioRAGsearch] loaded {len(_corpus)} chunks from {len(papers)} papers: {papers}")
    except Exception as exc:
        _load_error = str(exc)
        print(f"[bioRAGsearch] ERROR loading papers_data: {exc}")


_load_index()

_HTML = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>bioRAGsearch</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    :root {
      --navy:       #0C1F3F;
      --navy-hover: #162E5A;
      --blue-bg:    #EFF6FF;
      --blue-text:  #1D4ED8;
      --text-1:     #1E293B;
      --text-2:     #475569;
      --text-muted: #94A3B8;
      --border:     #E2E8F0;
      --card-bg:    #F8FAFC;
    }

    body {
      font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
      background: #fff;
      color: var(--text-1);
      line-height: 1.5;
      min-height: 100vh;
    }

    .site-header {
      padding: 52px 24px 40px;
      text-align: center;
    }

    .site-header h1 {
      font-size: 1.875rem;
      font-weight: 700;
      color: var(--navy);
      letter-spacing: -0.03em;
    }

    .site-header p {
      margin-top: 8px;
      font-size: 0.875rem;
      color: var(--text-muted);
    }

    hr { border: none; border-top: 1px solid var(--border); }

    main {
      max-width: 700px;
      margin: 0 auto;
      padding: 44px 24px 96px;
    }

    .search-row { display: flex; gap: 10px; }

    .search-row input {
      flex: 1;
      min-width: 0;
      padding: 11px 16px;
      border: 1.5px solid var(--border);
      border-radius: 8px;
      font-family: inherit;
      font-size: 0.9375rem;
      color: var(--text-1);
      outline: none;
      transition: border-color 0.15s;
      background: #fff;
    }

    .search-row input:focus { border-color: var(--navy); }
    .search-row input::placeholder { color: var(--text-muted); }

    .search-row button {
      display: flex;
      align-items: center;
      gap: 7px;
      padding: 11px 20px;
      background: var(--navy);
      color: #fff;
      border: none;
      border-radius: 8px;
      font-family: inherit;
      font-size: 0.875rem;
      font-weight: 600;
      cursor: pointer;
      white-space: nowrap;
      transition: background 0.15s, opacity 0.15s;
    }

    .search-row button:hover:not(:disabled) { background: var(--navy-hover); }
    .search-row button:disabled { opacity: 0.5; cursor: not-allowed; }

    .spinner {
      width: 14px; height: 14px;
      border: 2px solid rgba(255,255,255,.3);
      border-top-color: #fff;
      border-radius: 50%;
      animation: spin .7s linear infinite;
      display: none;
    }

    .loading .spinner   { display: block; }
    .loading .btn-label { display: none; }
    @keyframes spin { to { transform: rotate(360deg); } }

    .result { margin-top: 40px; }

    .section-label {
      font-size: 0.6875rem;
      font-weight: 600;
      letter-spacing: 0.1em;
      text-transform: uppercase;
      color: var(--text-muted);
      margin-bottom: 10px;
    }

    .answer-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 10px;
      padding: 22px 24px;
      font-size: 0.9375rem;
      line-height: 1.8;
      color: var(--text-1);
      white-space: pre-wrap;
      word-break: break-word;
    }

    .sources-block {
      margin-top: 20px;
      display: flex;
      align-items: center;
      gap: 10px;
      flex-wrap: wrap;
    }

    .tags { display: flex; flex-wrap: wrap; gap: 6px; }

    .tag {
      padding: 3px 12px;
      background: var(--blue-bg);
      color: var(--blue-text);
      border-radius: 999px;
      font-size: 0.8125rem;
      font-weight: 500;
    }

    .error-box {
      margin-top: 20px;
      padding: 14px 18px;
      background: #FEF2F2;
      border: 1px solid #FECACA;
      border-radius: 8px;
      color: #B91C1C;
      font-size: 0.875rem;
    }

    @media (max-width: 480px) {
      .search-row { flex-direction: column; }
      .search-row button { justify-content: center; }
    }
  </style>
</head>
<body>

<header class="site-header">
  <h1>bioRAGsearch</h1>
  <p>Ask questions about your research papers</p>
</header>
<hr />

<main>
  <form id="form" autocomplete="off">
    <div class="search-row">
      <input
        type="text"
        id="query"
        placeholder="What is the role of microglia in neuroinflammation?"
        required
      />
      <button type="submit" id="btn">
        <span class="spinner"></span>
        <span class="btn-label">Search</span>
      </button>
    </div>
  </form>

  <div id="error" class="error-box" hidden></div>

  <div id="result" class="result" hidden>
    <div class="section-label">Answer</div>
    <div class="answer-card" id="answer"></div>

    <div id="sources-block" class="sources-block" hidden>
      <span class="section-label" style="margin-bottom:0">Sources</span>
      <div class="tags" id="tags"></div>
    </div>
  </div>
</main>

<script>
  const form      = document.getElementById('form');
  const queryEl   = document.getElementById('query');
  const btn       = document.getElementById('btn');
  const errorEl   = document.getElementById('error');
  const resultEl  = document.getElementById('result');
  const answerEl  = document.getElementById('answer');
  const sourcesEl = document.getElementById('sources-block');
  const tagsEl    = document.getElementById('tags');

  form.addEventListener('submit', async (e) => {
    e.preventDefault();
    const query = queryEl.value.trim();
    if (!query) return;

    btn.disabled = true;
    btn.classList.add('loading');
    errorEl.hidden = true;
    resultEl.hidden = true;

    try {
      const res = await fetch('/search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ query }),
      });

      let data;
      try { data = await res.json(); } catch { data = {}; }

      if (!res.ok) {
        throw new Error(data.detail || `Error ${res.status}`);
      }

      answerEl.textContent = data.answer ?? '';

      tagsEl.innerHTML = '';
      if (data.sources?.length) {
        data.sources.forEach(src => {
          const tag = document.createElement('span');
          tag.className = 'tag';
          tag.textContent = src;
          tagsEl.appendChild(tag);
        });
        sourcesEl.hidden = false;
      } else {
        sourcesEl.hidden = true;
      }

      resultEl.hidden = false;
    } catch (err) {
      errorEl.textContent = err.message || 'Something went wrong. Please try again.';
      errorEl.hidden = false;
    } finally {
      btn.disabled = false;
      btn.classList.remove('loading');
    }
  });
</script>

</body>
</html>"""


class SearchRequest(BaseModel):
    query: str


@app.get("/")
async def root() -> HTMLResponse:
    return HTMLResponse(_HTML)


@app.get("/debug")
async def debug():
    def ls(path: str):
        try:
            return sorted(os.listdir(path))
        except Exception as e:
            return str(e)

    return {
        "file": __file__,
        "here": _HERE,
        "load_error": _load_error or None,
        "corpus_size": len(_corpus),
        "files_in_here": ls(_HERE),
        "files_in_parent": ls(os.path.dirname(_HERE)),
        "sys_path": sys.path[:5],
    }


@app.get("/papers")
async def list_papers():
    names = list(dict.fromkeys(paper for _, paper in _corpus))
    return {"count": len(names), "papers": names}


@app.post("/search")
async def search(req: SearchRequest):
    query = req.query.strip()
    if not query:
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="ANTHROPIC_API_KEY is not set")

    context_text = ""
    sources: list[str] = []

    if _bm25 and _corpus:
        scores = _bm25.get_scores(query.lower().split())
        ranked = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:5]
        hits = [(i, scores[i]) for i in ranked if scores[i] > 0]

        if hits:
            seen: set[str] = set()
            parts = []
            for idx, _ in hits:
                chunk, paper = _corpus[idx]
                parts.append(f"[{paper}]\n{chunk}")
                seen.add(paper)
            context_text = "\n\n---\n\n".join(parts)
            sources = list(seen)

    if not context_text:
        context_text = "No directly relevant passages were found in the available papers."

    prompt = (
        "You are a biomedical research assistant. "
        "Answer the following question using the provided excerpts from research papers. "
        "Be precise and scientific. Cite the paper names shown in brackets when referencing findings. "
        "If the excerpts do not contain enough information, say so clearly.\n\n"
        f"Question: {query}\n\n"
        f"Context:\n{context_text}"
    )

    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    return {"answer": message.content[0].text, "sources": sources}
