import json
import os

import anthropic
from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse
from pydantic import BaseModel
from rank_bm25 import BM25Okapi

app = FastAPI()

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(_HERE)
PUBLIC_DIR = os.path.join(_ROOT, "public")

# Pre-built index lives in api/papers_index.json (generated by scripts/index_papers.py).
# It sits alongside this file so Vercel bundles it automatically — no includeFiles needed.
_corpus: list[tuple[str, str]] = []  # (chunk, paper_display_name)
_bm25: BM25Okapi | None = None


def _load_index() -> None:
    global _corpus, _bm25
    index_path = os.path.join(_HERE, "papers_index.json")
    try:
        with open(index_path, encoding="utf-8") as f:
            data = json.load(f)
        _corpus = [(item["chunk"], item["paper"]) for item in data]
        _bm25 = BM25Okapi([c[0].lower().split() for c in _corpus])
        papers = list(dict.fromkeys(p for _, p in _corpus))
        print(f"[bioRAGsearch] loaded {len(_corpus)} chunks from {len(papers)} papers: {papers}")
    except Exception as exc:
        print(f"[bioRAGsearch] ERROR loading index: {exc}")


_load_index()


class SearchRequest(BaseModel):
    query: str


@app.get("/")
async def root() -> HTMLResponse:
    with open(os.path.join(PUBLIC_DIR, "index.html"), encoding="utf-8") as f:
        return HTMLResponse(f.read())


@app.get("/papers")
async def list_papers():
    names = list(dict.fromkeys(paper for _, paper in _corpus))
    return {"count": len(names), "papers": names}


@app.post("/search")
async def search(req: SearchRequest):
    query = req.query.strip()
    if not query:
        raise HTTPException(status_code=400, detail="Query cannot be empty")

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise HTTPException(status_code=500, detail="ANTHROPIC_API_KEY is not set")

    context_text = ""
    sources: list[str] = []

    if _bm25 and _corpus:
        scores = _bm25.get_scores(query.lower().split())
        ranked = sorted(range(len(scores)), key=lambda i: scores[i], reverse=True)[:5]
        hits = [(i, scores[i]) for i in ranked if scores[i] > 0]

        if hits:
            seen: set[str] = set()
            parts = []
            for idx, _ in hits:
                chunk, paper = _corpus[idx]
                parts.append(f"[{paper}]\n{chunk}")
                seen.add(paper)
            context_text = "\n\n---\n\n".join(parts)
            sources = list(seen)

    if not context_text:
        context_text = "No directly relevant passages were found in the available papers."

    prompt = (
        "You are a biomedical research assistant. "
        "Answer the following question using the provided excerpts from research papers. "
        "Be precise and scientific. Cite the paper names shown in brackets when referencing findings. "
        "If the excerpts do not contain enough information, say so clearly.\n\n"
        f"Question: {query}\n\n"
        f"Context:\n{context_text}"
    )

    client = anthropic.Anthropic(api_key=api_key)
    message = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=1024,
        messages=[{"role": "user", "content": prompt}],
    )

    return {"answer": message.content[0].text, "sources": sources}
